---
- name: Add mongo ppa key
  become: yes
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    state: present
- name: Add mongo sources list
  become: yes
  copy:
    mode: 0644
    dest: /etc/apt/sources.list.d/mongodb.list
    content: >
        deb https://repo.mongodb.org/apt/ubuntu {{ distro_type }}/mongodb-org/{{ mongodb_version }} multiverse
- name: Install mongo
  become: yes
  apt:
    name:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools
      - mongodb-org-mongos
    state: present
    update_cache: yes
  notify:
      - restart mongo
- name: Enable mongo service
  become: yes
  systemd:
    name: mongod.service
    enabled: yes
