---
- name: Add source repository into sources list
  become: true
  ansible.builtin.apt_repository:
    update_cache: true
    repo: ppa:deadsnakes/ppa
    state: present
- name: Install python system dependencies
  become: true
  apt:
    state: present
    name:
      - python{{ python_version }}
      - python{{ python_version }}-dev
      - python{{ python_version }}-venv
      # Needed for python ldap package
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
- name: Install pip
  become: true
  ansible.builtin.shell: curl https://bootstrap.pypa.io/get-pip.py | sudo python{{ python_version }}
- name: Install virtualenv
  become: true
  ansible.builtin.shell: python{{ python_version }} -m pip install virtualenv
# NOTE: We can't update default python3 binary on the system using update
# alternatives since it breaks apt, and a bunch of other system tools which
# depends on a specific Python version
- name: Write a file which tells st2 which Python version to use for Makefile targets
  ansible.builtin.lineinfile:
    path: /home/vagrant/.st2_python_binary
    line: /usr/bin/python{{ python_version }}
    create: yes
#- name: Set python{{ python_version }} as default python 3
#  become: true
#  ansible.builtin.shell: |
#    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python{{ python_version }} 1
#    update-alternatives --set python3 /usr/bin/python{{ python_version }}
#
#    # We change default python3 binary so we need a hack for apt to still work
#    cd  /usr/lib/python3/dist-packages
#    sudo cp apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.so || true
