---
- name: Add source repository into sources list
  become: true
  ansible.builtin.apt_repository:
    update_cache: true
    repo: ppa:deadsnakes/ppa
    state: present
- name: Install python system dependencies
  become: true
  apt:
    state: latest
    name:
      - python3.6
      - python3.6-dev
      - python3.6-venv
      # Needed for python ldap package
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev
- name: Install pip
  become: true
  ansible.builtin.shell: curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
- name: Install virtualenv
  become: true
  ansible.builtin.shell: python3.6 -m pip install virtualenv
- name: Set python3.6 as default python 3
  become: true
  ansible.builtin.shell: |
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
    sudo update-alternatives --set python3 /usr/bin/python3.6
