---
- name: Add RabbitMQ erlang repo key
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: F77F1EDA57EBB1CC
- name: Add RabbitMQ server repo key
  become: yes
  apt_key:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    state: present
- name: Add RabbitMQ Erlang apt repo list
  become: yes
  copy:
    mode: 0644
    dest: /etc/apt/sources.list.d/rabbitmq-erlang.list
    content: >
        deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ distro_type }} main
- name: Add RabbitMQ server apt repo list
  become: yes
  copy:
    mode: 0644
    dest: /etc/apt/sources.list.d/rabbitmq-server.list
    content: >
        deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ distro_type }} main
# This step is needed so correct latest versions of erlang packages get installed
- name: Install Erlang
  become: yes
  ansible.builtin.apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
    state: present
    update_cache: yes
    cache_valid_time: 0
- name: Install RabbitMQ
  become: yes
  apt:
    name:
      - rabbitmq-server={{ rabbitmq_version }}
    state: present
    update_cache: yes
  notify:
      - restart rabbitmq-server
- name: Enable rabbitmq-server service
  become: yes
  systemd:
    name: rabbitmq-server.service
