---
- name: Copy over st2 bashrc aliases and utilities
  copy:
    mode: 0644
    src: st2_bash_profile.sh
    dest: /home/vagrant/.st2_bash_profile.sh
- name: Add bash_profile entry
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bash_profile
    line: source /home/vagrant/.st2_bash_profile.sh
    create: yes
