---
- name: Install st2 system and build dependencies
  become: true
  apt:
    state: present
    name:
      - build-essential
      - libffi-dev
      - libssl-dev
      - libxslt1-dev
      - libxml2-dev
      - libyaml-dev
      - nodejs
      - shellcheck
- name: Add stanley user
  become: true
  user:
    name: stanley
    comment: Stackstorm User
- name: Allow stanley user to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^stanley'
    line: 'stanley ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: Generate and add SSH key for stanley user for remote actions  # noqa: no-changed-when
  become: true
  command: bash /vagrant/ansible/roles/st2_dev/files/generate_stanley_key.sh
