---
- name: restart mongo
  become: yes
  systemd:
    name: mongod
    state: restarted
- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted
- name: restart redis
  become: yes
  systemd:
    name: redis-server
    state: restarted
- name: restart rabbitmq-server
  become: yes
  systemd:
    name: rabbitmq-server
    state: restarted
